# Generated by Django 5.1.7 on 2025-03-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patient_id',
            field=models.IntegerField(default=1),
        ),
    ]
