# Generated by Django 5.1.7 on 2025-03-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_patient_id'),
        ('camas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='admission',
            name='cama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camas.cama'),
        ),
    ]
